AWSTemplateFormatVersion: '2010-09-09'
Description: 'FindMyLunch Application - API Gateway Certificate (us-east-1)'

Parameters:
  EnvironmentName:
    Description: Environment name (qa or prod)
    Type: String
    Default: qa
    AllowedValues:
      - qa
      - prod
    ConstraintDescription: must be either qa or prod
    
  DomainName:
    Description: Main domain name for the application (e.g., findmylunch.com)
    Type: String
    Default: findmylunch.net

  SubDomainPrefix:
    Description: Subdomain prefix for non-production environments (e.g., qa)
    Type: String
    Default: qa

Conditions:
  IsProduction: !Equals [!Ref EnvironmentName, "prod"]

Resources:
 # Route 53 Hosted Zone
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: !Sub "Hosted zone for ${DomainName} (${EnvironmentName} environment)"
      Tags:
        - Key: Name
          Value: !Sub "${DomainName}-hosted-zone"
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: FindMyLunch

  # API Gateway Certificate (us-east-1 specific for API Gateway custom domains)
  ApiGatewayCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "api.${DomainName}"
      SubjectAlternativeNames: !If
        - IsProduction
        - []  # Empty list for production, no additional SANs needed
        - !Sub "api.${SubDomainPrefix}.${DomainName}"  # Only add subdomain SAN for non-production
      ValidationMethod: DNS
      DomainValidationOptions: !If
        - IsProduction
        - # For production, only validate the main API domain
          - DomainName: !Sub "api.${DomainName}"
            HostedZoneId: !Ref HostedZone
        - # For non-production, validate both domains
          - DomainName: !Sub "api.${DomainName}"
            HostedZoneId: !Ref HostedZone
          - DomainName: !Sub "api.${SubDomainPrefix}.${DomainName}"
            HostedZoneId: !Ref HostedZone
      Tags:
        - Key: Name
          Value: !Sub "api.${DomainName}-certificate"
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: FindMyLunch

Outputs:
  ApiGatewayCertificateArn:
    Description: ACM Certificate ARN for API Gateway
    Value: !Ref ApiGatewayCertificate
    Export:
      Name: !Sub "${EnvironmentName}-FindMyLunch-ApiGatewayCertificateArn"