AWSTemplateFormatVersion: '2010-09-09'
Description: 'FindMyLunch Application - API Gateway Certificate (us-east-1)'

Parameters:
  EnvironmentName:
    Description: Environment name (qa or prod)
    Type: String
    Default: qa
    AllowedValues:
      - qa
      - prod
    ConstraintDescription: must be either qa or prod
    
  DomainName:
    Description: Main domain name for the application (e.g., findmylunch.com)
    Type: String
    Default: findmylunch.net

  SubDomainPrefix:
    Description: Subdomain prefix for non-production environments (e.g., qa)
    Type: String
    Default: qa

  HostedZoneId:
    Description: Route53 Hosted Zone ID for the domain
    Type: String

Conditions:
  IsProduction: !Equals [!Ref EnvironmentName, "prod"]

Resources:
  # API Gateway Certificate (us-east-1 specific for API Gateway custom domains)
  ApiGatewayCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "api.${DomainName}"
      SubjectAlternativeNames: !If
        - IsProduction
        - []  # Empty list for production, no additional SANs needed
        - !Sub "api.${SubDomainPrefix}.${DomainName}"  # Only add subdomain SAN for non-production
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub "api.${DomainName}"
          HostedZoneId: !Ref HostedZoneId
        - !If
          - IsProduction
          - !Ref AWS::NoValue
          - DomainName: !Sub "api.${SubDomainPrefix}.${DomainName}"
            HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Name
          Value: !Sub "api.${DomainName}-certificate"
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: FindMyLunch

Outputs:
  ApiGatewayCertificateArn:
    Description: ACM Certificate ARN for API Gateway
    Value: !Ref ApiGatewayCertificate
    Export:
      Name: !Sub "${EnvironmentName}-FindMyLunch-ApiGatewayCertificateArn"