AWSTemplateFormatVersion: '2010-09-09'
Description: 'FindMyLunch Application - Base Networking Infrastructure (Hosted Zone)'

Parameters:
  ArtifactBucketPrefix:
    Description: Name prefix of the S3 bucket containing templates/artifacts
    Type: String
    Default: findmylunch-artifacts

  EnvironmentName:
    Description: Environment name (qa or prod)
    Type: String
    Default: qa
    AllowedValues:
      - qa
      - prod
    ConstraintDescription: must be either qa or prod
    
  DomainName:
    Description: Main domain name for the application (e.g., findmylunch.com)
    Type: String
    Default: findmylunch.net

Conditions:
  IsProduction: !Equals [!Ref EnvironmentName, "prod"]

Resources:
  # Route 53 Hosted Zone
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: !Sub "Hosted zone for ${DomainName} (${EnvironmentName} environment)"
      Tags:
        - Key: Name
          Value: !Sub "${DomainName}-hosted-zone"
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: FindMyLunch

Outputs:
  # Route53 Outputs
  HostedZoneId:
    Description: Route53 Hosted Zone ID
    Value: !Ref HostedZone
    Export:
      Name: !Sub ${EnvironmentName}-FindMyLunch-HostedZoneId

  DomainNameOutput:
    Description: Domain name
    Value: !Ref DomainName
    Export:
      Name: !Sub ${EnvironmentName}-FindMyLunch-DomainName