AWSTemplateFormatVersion: '2010-09-09'
Description: 'WhatsForLunch Application - Networking Infrastructure (Nested Stack)'

Parameters:
  EnvironmentName:
    Description: Environment name (qa or prod)
    Type: String
    Default: qa
    AllowedValues:
      - qa
      - prod
    ConstraintDescription: must be either qa or prod
    
  DomainName:
    Description: Main domain name for the application (e.g., whatsforlunch.to)
    Type: String
    Default: whatsforlunch.to
    
  SubDomainPrefix:
    Description: Subdomain prefix for non-production environments (e.g., qa)
    Type: String
    Default: qa

  VpcCIDR:
    Description: CIDR block for the VPC
    Type: String
    Default: 10.0.0.0/16

  PublicSubnet1CIDR:
    Description: CIDR block for Public Subnet 1
    Type: String
    Default: 10.0.0.0/24

  PublicSubnet2CIDR:
    Description: CIDR block for Public Subnet 2
    Type: String
    Default: 10.0.1.0/24

  PrivateSubnet1CIDR:
    Description: CIDR block for Private Subnet 1
    Type: String
    Default: 10.0.2.0/24

  PrivateSubnet2CIDR:
    Description: CIDR block for Private Subnet 2
    Type: String
    Default: 10.0.3.0/24

Conditions:
  IsProduction: !Equals [!Ref EnvironmentName, 'prod']

Resources:
  # Route 53 Hosted Zone
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: !Sub "Hosted zone for ${DomainName} (${EnvironmentName} environment)"
      Tags:
        - Key: Name
          Value: !Sub "${DomainName}-hosted-zone"
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: WhatsForLunch

  # ACM Certificate for main domain and wildcard subdomains
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub "*.${DomainName}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZone
        - DomainName: !Sub "*.${DomainName}"
          HostedZoneId: !Ref HostedZone
      Tags:
        - Key: Name
          Value: !Sub "${DomainName}-certificate"
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: WhatsForLunch

  # API Gateway Certificate (us-east-1 specific for API Gateway custom domains)
  ApiGatewayCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "api.${DomainName}"
      SubjectAlternativeNames:
        - !If [IsProduction, !Ref AWS::NoValue, !Sub "api.${SubDomainPrefix}.${DomainName}"]
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub "api.${DomainName}"
          HostedZoneId: !Ref HostedZone
        - DomainName: !If [IsProduction, !Ref AWS::NoValue, !Sub "api.${SubDomainPrefix}.${DomainName}"]
          HostedZoneId: !Ref HostedZone
      Tags:
        - Key: Name
          Value: !Sub "api.${DomainName}-certificate"
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: WhatsForLunch

  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-whatsforlunch-vpc
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: WhatsForLunch

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-whatsforlunch-igw
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: WhatsForLunch

  # Attach Internet Gateway to VPC
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  # Public Subnets
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-whatsforlunch-public-subnet-1
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: WhatsForLunch
        - Key: Type
          Value: Public

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-whatsforlunch-public-subnet-2
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: WhatsForLunch
        - Key: Type
          Value: Public

  # Private Subnets
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-whatsforlunch-private-subnet-1
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: WhatsForLunch
        - Key: Type
          Value: Private

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref PrivateSubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-whatsforlunch-private-subnet-2
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: WhatsForLunch
        - Key: Type
          Value: Private

  # NAT Gateway Elastic IP
  NatGatewayEIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-whatsforlunch-nat-eip
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: WhatsForLunch

  # NAT Gateway
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-whatsforlunch-nat-gateway
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: WhatsForLunch

  # Public Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-whatsforlunch-public-routes
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: WhatsForLunch
        - Key: Type
          Value: Public

  # Default Public Route
  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # Public Subnet 1 Route Table Association
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  # Public Subnet 2 Route Table Association
  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2

  # Private Route Table
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-whatsforlunch-private-routes
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: WhatsForLunch
        - Key: Type
          Value: Private

  # Default Private Route
  DefaultPrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  # Private Subnet 1 Route Table Association
  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet1

  # Private Subnet 2 Route Table Association
  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet2

  # Security Groups
  # ALB Security Group
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Application Load Balancer
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: Allow HTTP from anywhere
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: Allow HTTPS from anywhere
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-whatsforlunch-alb-sg
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: WhatsForLunch

  # EC2 Security Group
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 instances
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: Allow HTTP from ALB
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: Allow HTTPS from ALB
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-whatsforlunch-ec2-sg
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: WhatsForLunch

  # RDS Security Group
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS PostgreSQL instances
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref EC2SecurityGroup
          Description: Allow PostgreSQL from EC2 instances
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-whatsforlunch-rds-sg
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: WhatsForLunch

Outputs:
  # Route53 and ACM Outputs
  HostedZoneId:
    Description: Route53 Hosted Zone ID
    Value: !Ref HostedZone
    Export:
      Name: !Sub ${EnvironmentName}-WhatsForLunch-HostedZoneId

  CertificateArn:
    Description: ACM Certificate ARN for CloudFront
    Value: !Ref Certificate
    Export:
      Name: !Sub ${EnvironmentName}-WhatsForLunch-CertificateArn

  ApiGatewayCertificateArn:
    Description: ACM Certificate ARN for API Gateway
    Value: !Ref ApiGatewayCertificate
    Export:
      Name: !Sub ${EnvironmentName}-WhatsForLunch-ApiGatewayCertificateArn

  DomainNameOutput:
    Description: Domain name
    Value: !Ref DomainName
    Export:
      Name: !Sub ${EnvironmentName}-WhatsForLunch-DomainName

  # VPC Outputs
  VPC:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub ${EnvironmentName}-WhatsForLunch-VPC

  PublicSubnet1:
    Description: Public Subnet 1 ID
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub ${EnvironmentName}-WhatsForLunch-PublicSubnet1

  PublicSubnet2:
    Description: Public Subnet 2 ID
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub ${EnvironmentName}-WhatsForLunch-PublicSubnet2

  PrivateSubnet1:
    Description: Private Subnet 1 ID
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub ${EnvironmentName}-WhatsForLunch-PrivateSubnet1

  PrivateSubnet2:
    Description: Private Subnet 2 ID
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub ${EnvironmentName}-WhatsForLunch-PrivateSubnet2

  ALBSecurityGroup:
    Description: Security Group ID for Application Load Balancer
    Value: !Ref ALBSecurityGroup
    Export:
      Name: !Sub ${EnvironmentName}-WhatsForLunch-ALBSecurityGroup

  EC2SecurityGroup:
    Description: Security Group ID for EC2 instances
    Value: !Ref EC2SecurityGroup
    Export:
      Name: !Sub ${EnvironmentName}-WhatsForLunch-EC2SecurityGroup

  RDSSecurityGroup:
    Description: Security Group ID for RDS instances
    Value: !Ref RDSSecurityGroup
    Export:
      Name: !Sub ${EnvironmentName}-WhatsForLunch-RDSSecurityGroup

  PublicSubnets:
    Description: List of Public Subnet IDs
    Value: !Join [ ",", [ !Ref PublicSubnet1, !Ref PublicSubnet2 ] ]
    Export:
      Name: !Sub ${EnvironmentName}-WhatsForLunch-PublicSubnets

  PrivateSubnets:
    Description: List of Private Subnet IDs
    Value: !Join [ ",", [ !Ref PrivateSubnet1, !Ref PrivateSubnet2 ] ]
    Export:
      Name: !Sub ${EnvironmentName}-WhatsForLunch-PrivateSubnets

  VpcCidr:
    Description: VPC CIDR Block
    Value: !Ref VpcCIDR
    Export:
      Name: !Sub ${EnvironmentName}-WhatsForLunch-VpcCidr